/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DuenoRegistro;
import controlador.HistorialRegistro;
import controlador.MascotaRegistro;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Dueno;
import modelo.Historial;
import modelo.Mascota;

/**
 *
 * @author matia
 */
public class Form_Busqueda extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Busqueda.class.getName());

    /**
     * Creates new form Form_Busqueda
     */
    public Form_Busqueda() {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/huellas icon.png"));
this.setIconImage(icon);
        this.setTitle("Busqueda Veterinaria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcb_tipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jbtn_buscar = new javax.swing.JButton();
        jbtn_buscarTodo = new javax.swing.JButton();
        jtxt_busqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_resultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BUSCADOR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mascota", "Dueño", "Historial" }));
        jcb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_tipoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar por:");

        jbtn_buscar.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        jbtn_buscarTodo.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_buscarTodo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtn_buscarTodo.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_buscarTodo.setText("Listar todo");
        jbtn_buscarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarTodoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ingrede el id o nombre:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jbtn_buscar)
                .addGap(30, 30, 30)
                .addComponent(jbtn_buscarTodo)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar)
                    .addComponent(jbtn_buscarTodo)
                    .addComponent(jtxt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jtbl_resultados.setBackground(new java.awt.Color(204, 204, 204));
        jtbl_resultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", ""
            }
        ));
        jScrollPane1.setViewportView(jtbl_resultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_tipoActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();

        switch (jcb_tipo.getSelectedItem().toString()) {

            case "Mascota":
                modelo.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Especie", "Raza", "Edad", "Dueño"});
                break;

            case "Dueño":
                modelo.setColumnIdentifiers(new Object[]{"ID", "RUT", "Nombre", "Teléfono", "Dirección"});
                break;

            case "Historial":
                modelo.setColumnIdentifiers(new Object[]{"ID", "Fecha", "Motivo", "Diagnóstico", "Tratamiento", "ID Mascota"});
                break;
        }

        jtbl_resultados.setModel(modelo);
    }//GEN-LAST:event_jcb_tipoActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        String tipo = jcb_tipo.getSelectedItem().toString();
        String valor = jtxt_busqueda.getText().trim();

        DefaultTableModel modelo = (DefaultTableModel) jtbl_resultados.getModel();
        modelo.setRowCount(0);

        if (valor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID o Nombre");
            return;
        }

        switch (tipo) {

            case "Mascota":
                MascotaRegistro rm = new MascotaRegistro();

                // si es ID numérico → busca por ID
                try {
                    int id = Integer.parseInt(valor);
                    Mascota m = rm.buscarPorId(id);

                    if (m != null) {
                        modelo.addRow(new Object[]{m.getId_mascota(), m.getNombre(), m.getEspecie(), m.getRaza(), m.getEdad(), m.getId_dueno()});
                    }

                } catch (NumberFormatException e) {
                    // buscar por nombre
                    for (Mascota m : rm.buscarPorNombre(valor)) {
                        modelo.addRow(new Object[]{m.getId_mascota(), m.getNombre(), m.getEspecie(), m.getRaza(), m.getEdad(), m.getId_dueno()});
                    }
                }
                break;

            case "Dueño":
                DuenoRegistro rd = new DuenoRegistro();
                try {
                    int id = Integer.parseInt(valor);
                    Dueno d = rd.buscarPorId(id);
                    if (d != null) {
                        modelo.addRow(new Object[]{d.getId_dueno(), d.getRut(), d.getNombre(), d.getTelefono(), d.getDireccion()});
                    }
                } catch (NumberFormatException e) {
                    for (Dueno d : rd.buscarPorNombre(valor)) {
                        modelo.addRow(new Object[]{d.getId_dueno(), d.getRut(), d.getNombre(), d.getTelefono(), d.getDireccion()});
                    }
                }
                break;

            case "Historial":
                HistorialRegistro rh = new HistorialRegistro();

                // Intentar buscar por ID si el usuario escribió un número
                try {
                    int id = Integer.parseInt(valor);
                    Historial h = rh.buscarPorId(id);

                    if (h != null) {
                        modelo.addRow(new Object[]{
                            h.getId_historial(),
                            h.getFecha(),
                            h.getMotivo(),
                            h.getDiagnostico(),
                            h.getTratamiento(),
                            h.getId_mascota()
                        });
                    } else {
                        JOptionPane.showMessageDialog(this, "No existe historial con ese ID");
                    }

                } catch (NumberFormatException e) {

                    // SI NO ES NÚMERO → BUSCAR POR NOMBRE DE MASCOTA
                    List<Historial> lista = rh.buscarPorNombreMascota(valor);

                    if (lista.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No hay historiales para esa mascota");
                    } else {
                        for (Historial h : lista) {
                            modelo.addRow(new Object[]{
                                h.getId_historial(),
                                h.getFecha(),
                                h.getMotivo(),
                                h.getDiagnostico(),
                                h.getTratamiento(),
                                h.getId_mascota()
                            });
                        }
                    }
                }
                break;
        }
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jbtn_buscarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarTodoActionPerformed
        String tipo = jcb_tipo.getSelectedItem().toString();

        DefaultTableModel modelo = (DefaultTableModel) jtbl_resultados.getModel();
        modelo.setRowCount(0);

        switch (tipo) {
            case "Mascota":
                for (Mascota m : new MascotaRegistro().buscarTodos()) {
                    modelo.addRow(new Object[]{m.getId_mascota(), m.getNombre(), m.getEspecie(), m.getRaza(), m.getEdad(), m.getId_dueno()});
                }
                break;

            case "Dueño":
                for (Dueno d : new DuenoRegistro().buscarTodos()) {
                    modelo.addRow(new Object[]{d.getId_dueno(), d.getRut(), d.getNombre(), d.getTelefono(), d.getDireccion()});
                }
                break;

            case "Historial":
                for (Historial h : new HistorialRegistro().buscarTodos()) {
                    modelo.addRow(new Object[]{h.getId_historial(), h.getFecha(), h.getMotivo(), h.getDiagnostico(), h.getTratamiento(), h.getId_mascota()});
                }
                break;
        }
    }//GEN-LAST:event_jbtn_buscarTodoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Form_Busqueda().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_buscarTodo;
    private javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JTable jtbl_resultados;
    private javax.swing.JTextField jtxt_busqueda;
    // End of variables declaration//GEN-END:variables
}
