/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.HistorialRegistro;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Historial;

/**
 *
 * @author matia
 */
public class Form_Historial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_Historial.class.getName());

    /**
     * Creates new form Form_Historial
     */
    public Form_Historial() {
        initComponents();
        setLocationRelativeTo(null);
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/huellas icon.png"));
this.setIconImage(icon);
        this.setTitle("Historial Veterinaria");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxt_motivo = new javax.swing.JTextField();
        jtxt_dia = new javax.swing.JTextField();
        jtxt_diagnostico = new javax.swing.JTextField();
        jtxt_tratamiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxt_idHistorial = new javax.swing.JTextField();
        jtxt_mes = new javax.swing.JTextField();
        jtxt_agnio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtxt_idMascota = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jbtn_agregar = new javax.swing.JButton();
        jbtn_eliminar = new javax.swing.JButton();
        jbtn_buscar = new javax.swing.JButton();
        jbtn_actualizar = new javax.swing.JButton();
        jbtn_listar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jbtl_datos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTIÓN DE HISTORIAL", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Motivo:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Diagnostico:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tratamiento:");

        jtxt_motivo.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_motivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_motivoActionPerformed(evt);
            }
        });

        jtxt_dia.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_diaActionPerformed(evt);
            }
        });

        jtxt_diagnostico.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_diagnostico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_diagnosticoActionPerformed(evt);
            }
        });

        jtxt_tratamiento.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_tratamiento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jtxt_tratamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_tratamientoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID Historial:");

        jtxt_idHistorial.setForeground(new java.awt.Color(153, 153, 153));
        jtxt_idHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_idHistorialActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("/");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("/");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("ID Mascota:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_idHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxt_agnio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxt_diagnostico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(jtxt_tratamiento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxt_idMascota))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_idHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_tratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_agnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jtxt_diagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxt_motivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jtxt_idMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtn_agregar.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_agregar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jbtn_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_agregar.setText("Agregar");
        jbtn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarActionPerformed(evt);
            }
        });

        jbtn_eliminar.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_eliminar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtn_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_eliminar.setText("Eliminar");
        jbtn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarActionPerformed(evt);
            }
        });

        jbtn_buscar.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_buscar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_buscar.setText("Buscar");
        jbtn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarActionPerformed(evt);
            }
        });

        jbtn_actualizar.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_actualizar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtn_actualizar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_actualizar.setText("Actualizar");
        jbtn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarActionPerformed(evt);
            }
        });

        jbtn_listar.setBackground(new java.awt.Color(51, 153, 255));
        jbtn_listar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtn_listar.setForeground(new java.awt.Color(255, 255, 255));
        jbtn_listar.setText("Listar");
        jbtn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.setBackground(new java.awt.Color(153, 204, 255));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jbtl_datos.setBackground(new java.awt.Color(102, 204, 255));
        jbtl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Historial", "Fecha", "Motivo", "Diagnostico", "Tratamiento", "Id Mascota"
            }
        ));
        jScrollPane1.setViewportView(jbtl_datos);
        if (jbtl_datos.getColumnModel().getColumnCount() > 0) {
            jbtl_datos.getColumnModel().getColumn(2).setResizable(false);
        }

        jTabbedPane1.addTab("Lista Historiales", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_motivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_motivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_motivoActionPerformed

    private void jtxt_diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_diaActionPerformed

    private void jtxt_diagnosticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_diagnosticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_diagnosticoActionPerformed

    private void jtxt_idHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_idHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_idHistorialActionPerformed

    private void jbtn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarActionPerformed

        String motivo, diagnostico, tratamiento;
        String dia, mes, agnio, fechaStr;
        Date fecha = null;
        int id_mascota = 0;

        // CAPTURAR CAMPOS
        motivo = jtxt_motivo.getText();
        diagnostico = jtxt_diagnostico.getText();
        tratamiento = jtxt_tratamiento.getText();

        dia = jtxt_dia.getText();
        mes = jtxt_mes.getText();
        agnio = jtxt_agnio.getText();

        // ID MASCOTA (FK)
        try {
            id_mascota = Integer.parseInt(jtxt_idMascota.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID de mascota válido", "Validación", 2);
            return;
        }

        // PARSEAR FECHA
        fechaStr = dia + "/" + mes + "/" + agnio;
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");

        try {
            fecha = formato.parse(fechaStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Ingrese fecha dd/mm/aaaa", "Validación", 2);
            return;
        }

        // VALIDAR CAMPOS
        if (motivo.isEmpty() || diagnostico.isEmpty() || tratamiento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Complete todos los campos", "Validación", 2);
            return;
        }

        // CREAR OBJETO
        Historial historial = new Historial(
                0, fecha, motivo, diagnostico, tratamiento, id_mascota
        );

        // GUARDAR EN BD
        HistorialRegistro reg = new HistorialRegistro();

        if (reg.agregar(historial)) {
            JOptionPane.showMessageDialog(this, "Historial agregado!");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo guardar.", "Error", 3);
        }


    }//GEN-LAST:event_jbtn_agregarActionPerformed

    private void jbtn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarActionPerformed
        int id = 0;

    try {
        id = Integer.parseInt(jtxt_idHistorial.getText());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "ID inválido");
        return;
    }

    HistorialRegistro reg = new HistorialRegistro();

    if (reg.eliminar(id)) {
        JOptionPane.showMessageDialog(this, "Historial eliminado!");
        limpiar();
    } else {
        JOptionPane.showMessageDialog(this, "No se pudo eliminar.");
    }
    }//GEN-LAST:event_jbtn_eliminarActionPerformed

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
        int id = 0;

        try {
            id = Integer.parseInt(jtxt_idHistorial.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID válido");
            return;
        }

        HistorialRegistro reg = new HistorialRegistro();
        Historial h = reg.buscarPorId(id);

        if (h != null) {

            // FECHA DESCOMPUESTA
            Calendar cal = Calendar.getInstance();
            cal.setTime(h.getFecha());

            jtxt_dia.setText(String.valueOf(cal.get(Calendar.DAY_OF_MONTH)));
            jtxt_mes.setText(String.valueOf(cal.get(Calendar.MONTH) + 1));
            jtxt_agnio.setText(String.valueOf(cal.get(Calendar.YEAR)));

            jtxt_motivo.setText(h.getMotivo());
            jtxt_diagnostico.setText(h.getDiagnostico());
            jtxt_tratamiento.setText(h.getTratamiento());
            jtxt_idMascota.setText(String.valueOf(h.getId_mascota()));

            JOptionPane.showMessageDialog(this, "Historial encontrado!");
        } else {
            JOptionPane.showMessageDialog(this, "No existe historial con ese ID");
        }
    }//GEN-LAST:event_jbtn_buscarActionPerformed

    private void jbtn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarActionPerformed
        int id = 0;
        int id_mascota = 0;

        try {
            id = Integer.parseInt(jtxt_idHistorial.getText());
            id_mascota = Integer.parseInt(jtxt_idMascota.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "IDs inválidos");
            return;
        }

        String motivo = jtxt_motivo.getText();
        String diagnostico = jtxt_diagnostico.getText();
        String tratamiento = jtxt_tratamiento.getText();

        String fechaStr = jtxt_dia.getText() + "/" + jtxt_mes.getText() + "/" + jtxt_agnio.getText();
        Date fecha = null;

        try {
            fecha = new SimpleDateFormat("dd/MM/yyyy").parse(fechaStr);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Fecha inválida");
            return;
        }

        Historial h = new Historial(id, fecha, motivo, diagnostico, tratamiento, id_mascota);
        HistorialRegistro reg = new HistorialRegistro();

        if (reg.actualizar(h)) {
            JOptionPane.showMessageDialog(this, "Historial actualizado!");
            limpiar();
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo actualizar.");
        }
    }//GEN-LAST:event_jbtn_actualizarActionPerformed

    private void jbtn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jbtl_datos.getModel();
    modelo.setRowCount(0);

    HistorialRegistro reg = new HistorialRegistro();

    for (Historial h : reg.buscarTodos()) {

        modelo.addRow(new Object[]{
            h.getId_historial(),
            h.getFecha(),
            h.getMotivo(),
            h.getDiagnostico(),
            h.getTratamiento(),
            h.getId_mascota()
        });
    }
    }//GEN-LAST:event_jbtn_listarActionPerformed

    private void jtxt_tratamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_tratamientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_tratamientoActionPerformed

    public void limpiar() {
       jtxt_idHistorial.setText("");
    jtxt_dia.setText("");
    jtxt_mes.setText("");
    jtxt_agnio.setText("");
    jtxt_motivo.setText("");
    jtxt_diagnostico.setText("");
    jtxt_tratamiento.setText("");
    jtxt_idMascota.setText("");
    this.jtxt_idHistorial.requestFocus();
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new Form_Historial().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jbtl_datos;
    private javax.swing.JButton jbtn_actualizar;
    private javax.swing.JButton jbtn_agregar;
    private javax.swing.JButton jbtn_buscar;
    private javax.swing.JButton jbtn_eliminar;
    private javax.swing.JButton jbtn_listar;
    private javax.swing.JTextField jtxt_agnio;
    private javax.swing.JTextField jtxt_dia;
    private javax.swing.JTextField jtxt_diagnostico;
    private javax.swing.JTextField jtxt_idHistorial;
    private javax.swing.JTextField jtxt_idMascota;
    private javax.swing.JTextField jtxt_mes;
    private javax.swing.JTextField jtxt_motivo;
    private javax.swing.JTextField jtxt_tratamiento;
    // End of variables declaration//GEN-END:variables
}
